### PR TITLE
Create unit tests #22

### LINKED ISSUE #22: Create unit tests
# Description
We need to figure out a strategy for writing unit tests against the plugin code and the UI code so that we can have confidence in our code base and confidence when making changes.

### PR DESCRIPTION
**Pull request by paustint**
~~**This is still a work in progress, do not merge**~~

This depends on #14 being merged first, as it was branched from PR #21

- Setup unit tests
    - Added unit tests for all file types including parsing, adding properties, updating properties, and ensuring file integrity
- Added unit tests for CSS files
- Updated `.gitignore` to include a lot more coverage based on gitignore.io
- added `.prettierrc` (copied from #27)

### TODO:

- [x] unit tests for other filetypes
- [x] unit test to ensure files are updated correctly and not corrupted
- [x] Update travis to auto-run tests
- [x] Configure travis to run tests
- [x] Fix Failing Tests
    - [x] HTML/Vue/Svelte fail if `<script>` tag and CSS property start on same line

## Todo in future ticket
- [ ] UI unit tests

resolves #22

### CODE REVIEW

**Comment by Raathigesh** [comment]
This looks good to me 👍

**Comment by paustint** [comment]
@Raathigesh

1. Can you configure Travis CI for this project to auto-test on commits? I have updated the travis CI to run tests and want to try it out to see if it works (you can look at `.travis.yml` to see changes)
2. I have spent a lot of time re-working the unit test and adding unit tests for all file types.  What I found is that there is a bug with HTML/Svelte/Vue files if the CSS property starts on the same line as the `<style>` tag, the column number is off by one and causing the `.` to be repeated.
    - Take a look at the test case files for each filetype to look at the coverage. It should be fairly easy to add more tests in the future if we find any other edge-cases.
    - I will work on fixing the HTML bug soon (maybe not today)

### Test Results

image

image

**Comment by Raathigesh** [comment]
Hey @paustint,

This is so awesome. Is there anything I can do to help with this PR. I'll try to set up the CI.

**Comment by Raathigesh** [comment]
Hey, I did enable Travis for this repo. Hopefully, as soon as merge this PR, CI would run the tests. https://travis-ci.org/Raathigesh/fabulous

**Comment by Raathigesh** [comment]
@all-contributors please add @paustint for bug, doc, infra and review

**Pull request merged**
